Ejaraat/urls.py
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.i18n import set_language

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("core.urls")),
]
urlpatterns += i18n_patterns(
    path("set-language/", set_language, name="set_language"),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.landing, name="landing"),
    path("home/", views.home, name="home"),
    path("add/", views.add_property, name="add_property"),
    path("rent_property/<int:pk>/", views.rent_property, name="rent_property"),
    path("edit_rental/<int:pk>/", views.edit_rental, name="edit_rental"),
    path("all_properties/", views.all_properties, name="all_properties"),
    path("delete_property/<int:pk>", views.delete_property, name="delete_property"),
    path("edit_property/<int:pk>", views.edit_property, name="edit_property"),
    path("view_property/<int:pk>", views.view_property, name="view_property"),
    path("mark_as_paid/<int:pk>", views.mark_as_paid, name="mark_as_paid"),
    path("empty_property/<int:pk>", views.empty_property, name="empty_property"),
    path("search_all_properties/", views.search_all_properties, name="search_all_properties"),
    path("not_developed/", views.not_developed, name="not_developed"),
    path("all_tenants/", views.all_tenants, name="all_tenants"),
    path("search_all_tenants/", views.search_all_tenants, name="search_all_tenants"),
]

core/models.py
from datetime import timedelta, date
from dateutil.relativedelta import relativedelta

from django.contrib.auth.models import User
from django_countries.fields import CountryField
from django.db import models
from django.utils.translation import gettext_lazy as _

from .utils import get_next_payment


class Property(models.Model):
    """
    A property model
    """

    class Meta:
        verbose_name = "Property"
        verbose_name_plural = "Properties"

    TYPE_CHOICES = (
        ("R", _("Room")),
        ("A", _("Apartment")),
        ("H", _("House")),
        ("V", _("Villa")),
        ("O", _("Office")),
        ("S", _("Store")),
    )

    CURRENCY_CHOICES = (
        ("", _("Select Currency")),
        ("USD", _("US Dollars")),
        ("EUR", _("European Euro")),
        ("SDG", _("Sudanese Pound")),
        ("EGP", _("Egyptian Pound")),
    )

    # property data
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name="Landlord",
    )
    name = models.CharField(max_length=20)
    property_type = models.CharField(
        max_length=25, choices=TYPE_CHOICES, default=TYPE_CHOICES[1]
    )
    country = CountryField(blank_label=_("Select Country"))
    city = models.CharField(max_length=25)
    address = models.CharField(max_length=100)
    currency = models.CharField(
        max_length=3, null=True, blank=True, choices=CURRENCY_CHOICES
    )
    is_rented = models.BooleanField(default=False)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} - belong to {self.user} / {self.property_type}"

    def get_translated_currency(self):
        """
        Get the translated currency based on the selected currency
        """

        currency_map = {
            "USD": _("USD"),
            "EUR": _("EUR"),
            "SDG": _("SDG"),
            "EGP": _("EGP"),
        }
        return currency_map.get(self.currency, self.currency)

    def save(self, *args, **kwargs):
        """
        Set the currency based on the country
        """

        country_currency_map = {
            "US": "USD",
            "EU": "EUR",
            "SD": "SDG",
            "EG": "EGP",
        }
        if not self.currency:
            self.currency = country_currency_map.get(self.country, "USD")
        super().save(*args, **kwargs)


class Tenant(models.Model):
    """
    A tenant model
    """

    landlord = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=14)
    id_image = models.ImageField(
        upload_to="tenants_ID",
        null=True,
        blank=True,
        help_text="[Passport, National ID]",
    )

    def __str__(self):
        return f"{self.name} / {self.landlord}'s Tenant" 


class RentProperty(models.Model):
    """
    A model to represent the rental details of a property
    """

    class Meta:
        verbose_name = "Rent Property"
        verbose_name_plural = "Rent Properties"

    PAYMENT_OPTIONS = (
        ("1", _("Daily")),
        ("7", _("Weekly")),
        ("30", _("Monthly")),
        ("365", _("Yearly")),
    )

    STATUS_OPTIONS = (
        ("paid", _("Paid")),
        ("unpaid", _("Unpaid")),
        ("pending", _("Pending")),
        ("overdue", _("Overdue")),
    )

    # tenant data
    tenant = models.ForeignKey(
        Tenant, on_delete=models.CASCADE, related_name="tenant_rentals"
    )

    # property data
    property = models.ForeignKey(
        Property,
        verbose_name="Property to Rent",
        on_delete=models.CASCADE,
        related_name="property_rentals",
    )
    payment = models.CharField(
        choices=PAYMENT_OPTIONS, max_length=10, default=PAYMENT_OPTIONS[2]
    )
    price = models.IntegerField(help_text=_("Format: 12500"))
    damage_deposit = models.IntegerField(null=True, blank=True)
    start_date = models.DateField(default=date.today)
    end_date = models.DateField(default=date.today() + timedelta(days=30))
    status = models.CharField(max_length=10, choices=STATUS_OPTIONS, default="paid")
    contract = models.ImageField(upload_to="contracts", null=True, blank=True)

    def __str__(self):
        return f"{self.property.name} - Rented to {self.tenant.name} by {self.property.user}"

    def get_payment_period(self):
        """
        Get the payment period based on the payment interval
        """

        payment = int(self.payment)
        if payment == 7:
            return _("week")
        elif payment == 30:
            return _("month")
        elif payment == 365:
            return _("year")
        else:
            return _("day")

    def expiring_contracts(self):
        """
        Check if the contract is expiring in the next 30 days
        """

        end_date = self.end_date
        today = date.today()

        if today >= end_date - timedelta(days=30):
            return True, (end_date - today).days

    def get_next_payment(self):
        """
        Calculate the next payment date based on the payment interval
        """

        return get_next_payment(self.payment, self.start_date, self.end_date)

    # def reset_payment_status(self):
    #     """
    #     Resets the payment status based on the payment frequency (daily, weekly, monthly, or yearly).
    #     This should reset on the next payment date based on the interval.
    #     """
    #     today = date.today()
    #     interval_days = int(self.payment)

    #     if self.status == "paid":
    #         # Reset logic for different payment intervals
    #         if interval_days == 1:
    #             # Reset every day
    #             self.status == "pending"
    #             self.save()

    #         elif interval_days == 7:
    #             # Reset every 7 days from start_date
    #             next_payment_day = self.start_date + timedelta(weeks=(today - self.start_date).days // 7 + 1)
    #             if today == next_payment_day:
    #                 self.status == "pending"
    #                 self.save()

    #         elif interval_days == 30:
    #             # Reset every month on the same day as start_date
    #             next_payment_month = self.start_date + relativedelta(months=(today.year - self.start_date.year) * 12 + today.month - self.start_date.month + 1)
    #             if today == next_payment_month:
    #                 self.status == "pending"
    #                 self.save()

    #         elif self.payment == 365:
    #             # Reset every year on the same day as start_date
    #             next_payment_year = self.start_date + relativedelta(years=(today.year - self.start_date.year + 1))
    #             if today == next_payment_year:
    #                 self.status == "pending"
    #                 self.save()

    # def expected_income(self):
    #     """
    #     Calculate the expected income from the property based on the payment interval
    #     """

    #     interval_days = int(self.payment)
    #     price = self.price
    #     expected_income = 0
    #     end_date = self.end_date
    #     start_date = self.start_date

    #     current_date = start_date

    #     # Use relativedelta for better handling of monthly or yearly intervals
    #     while current_date <= end_date:
    #         expected_income += price

    #         # Check if it's a monthly interval, for example 30 days
    #         if interval_days == 30:
    #             current_date += relativedelta(months=1)  # Move by 1 month
    #         else:
    #             current_date += timedelta(days=interval_days)  # For other intervals

    #     return (
    #         format_number(expected_income, locale="en_US")
    #         if expected_income == price
    #         else format_number(expected_income - price, locale="en_US")
    #     )


class RentHistory(models.Model):
    """
    A model to represent the rent history of a property
    """

    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    tenant = models.ForeignKey(Tenant, on_delete=models.SET_NULL, null=True, blank=True)
    price = models.IntegerField()
    damage_deposit = models.IntegerField(null=True, blank=True)
    payment_type = models.CharField(max_length=50)
    start_date = models.DateField()
    end_date = models.DateField()
    contract = models.ImageField(
        upload_to="rent_history_contracts", null=True, blank=True
    )

    class Meta:
        verbose_name = "Rent History"
        verbose_name_plural = "Rent Histories"
        ordering = ["-end_date"]

    def __str__(self):
        property_name = self.property.name
        tenant_name = self.tenant.name if self.tenant else "Unknown Tenant"
        return f"RentHistory for {property_name} rented by {tenant_name}"


class RecentActivity(models.Model):
    """
    A model to represent recent activities for a user
    """

    ACTIVITIES_OPTIONS = (
        ("rent", _("You've rented this property.")),
        ("payment", _("You've received a payment for the property.")),
        ("contract", _("You've successfully renewed the contract for the property.")),
        ("overdue", _("Payment overdue for the property.")),
        ("add", _("You've added a new property.")),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    activity_type = models.CharField(max_length=50, choices=ACTIVITIES_OPTIONS)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Recent Activity"
        verbose_name_plural = "Recent Activities"
        ordering = ["-timestamp"]

    def __str__(self):
        return f"{self.user} {self.activity_type} for {self.property.name} on {self.timestamp}"


class Notifications(models.Model):
    """
    A model to represent notifications for a user
    """

    user = models.ForeignKey(User, on_delete=models.CASCADE)

templates/includes/language_menu.html
{% load i18n %}

<form action="{% url 'set_language' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{% url 'home' %}" />
    <div class="p-2">
        <h4
            class="dropdown m-0 p-0"
            type="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
        >
            <i class="bi bi-translate"></i>
        </h4>
        <ul class="dropdown-menu shadow-sm border-0 rounded-4 mt-1">
            <button
                type="submit"
                class="dropdown-item rounded-2"
                name="language"
                value="en"
            >
                {% trans "English" %}
            </button>
            <button
                type="submit"
                class="dropdown-item rounded-2"
                name="language"
                value="ar"
            >
                {% trans "Arabic" %}
            </button>
        </ul>
    </div>
</form>

templates/includes/overview_cards.html
{% load i18n %}


<div>
    <h2>{% trans "Overview" %}</h2>
</div>
<div class="mt-lg-3 row row-cols-2 row-cols-lg-3">
    <div class="col p-3">
        <a href="#" data-bs-toggle="modal" data-bs-target="#availablePropertiesModal" style="text-decoration: none">
            <div class="card card-overview shadow-sm p-3 border-0" style="height: 130px">
                <h5>{% trans "Available Properties" %}</h5>
                <h3 class="card-value pt-3">{{ available_properties.count }}</h3>
            </div>
        </a>
    </div>
    <div class="col p-3">
        <a href="#" data-bs-toggle="modal" data-bs-target="#occupiedPropertiesModal" style="text-decoration: none">
            <div class="card card-overview shadow-sm p-3 border-0" style="height: 130px;">
                <h5>{% trans "Occupied Properties" %}</h5>
                <h3 class="card-value pt-3">{{ rented_properties.count }}</h3>
            </div>
        </a>
    </div>
</div>

templates/includes/recent_activities.html
{% load i18n %}
{% load static %}


<div id="recent-activities">
    <div class="activities-header d-md-none d-flex justify-content-between align-items-center">
        <h5>{% trans "Recent Activities" %}</h5>
        <i class="close-recent-activities bi bi-x-lg" style='cursor: pointer;'></i>
    </div>
    <div class="activities-header d-md-inline-block d-none w-100">
        <h5><i class="bi bi-clock"></i> {% trans "Recent Activities" %}</h5>
        <p class="text-muted m-0" style="font-size: 14px;">{% trans "Recent activities will be logged here" %}</p>
    </div>
    
    {% if recent_activities %}
        <!-- Timeline for Recent Activities -->
        <div class="timeline w-100">
            {% for activity in recent_activities %}
                {% comment %} adding notification {% endcomment %}
                {% if activity.activity_type == "add" %}
                    <div class="timeline-item mb-4">
                        <div class="timeline-icon bg-secondary text-white" >
                            <i class="bi bi-building-add"></i>
                        </div>
                        <div class="timeline-content">
                            <p class="text-muted p-0 m-0">
                                {{ activity.get_activity_type_display }}
                                <a hx-get="{% url "view_property" activity.property.id %}" hx-target="#main-content" style="color: var(--secondary-color); word-wrap: break-word; word-break: break-word">
                                    {{ activity.property.name|title }}
                                </a>
                            </p>
                            <small class="text-muted">{{ activity.timestamp|date:"d M Y - h:i A" }}</small>
                        </div>
                    </div>
                {% comment %} end of adding notification {% endcomment %}

                {% comment %} rent notifications {% endcomment %}
                {% elif activity.activity_type == "rent" %}
                    <div class="timeline-item mb-4">
                        <div class="timeline-icon text-white" style="background-color: var(--primary-color)">
                            <i class="bi bi-house-fill"></i>
                        </div>
                        <div class="timeline-content">
                            <p class="text-muted p-0 m-0">
                                {{ activity.get_activity_type_display }}
                                <a hx-get="{% url "view_property" activity.property.id %}" hx-target="#main-content" style="color: var(--secondary-color); word-wrap: break-word; word-break: break-word">
                                    {{ activity.property.name|title }}
                                </a>
                            </p>
                            <small class="text-muted">{{ activity.timestamp|date:"d M Y - h:i A" }}</small>
                        </div>
                    </div>
                {% comment %} end of rent notifications {% endcomment %}

                {% comment %} payment notifications {% endcomment %}
                {% elif activity.activity_type == "payment" %}
                    <div class="timeline-item mb-4">
                        <div class="timeline-icon text-white" style="background-color: var(--success-color)">
                            <i class="bi bi-cash-stack"></i>
                        </div>
                        <div class="timeline-content">
                            <p class="text-muted p-0 m-0">
                                {{ activity.get_activity_type_display }}
                                <a hx-get="{% url "view_property" activity.property.id %}" hx-target="#main-content" style="color: var(--secondary-color); word-wrap: break-word; word-break: break-word">
                                    {{ activity.property.name|title }}
                                </a>
                            </p>
                            <small class="text-muted">{{ activity.timestamp|date:"d M Y - h:i A" }}</small>
                        </div>
                    </div>
                {% comment %} end of payment notifications {% endcomment %}
                {% endif %}
            {% endfor %}
        </div>
    {% endif %}
</div>

templates/includes/search.html
{% load i18n %}


<form class="d-lg-inline-block px-1">
    <input
        class="form-control rounded-5"
        hx-get="{% url 'search_all_properties' %}"
        hx-target="#main-content"
        hx-swap="innerHTML"
        hx-trigger="keyup changed delay:500ms"
        type="search"
        placeholder="{% trans "Search by Name, Country" %}"
        aria-label="Search"
        name="q"
    >
</form>

templates/includes/view_property.html
{% load i18n %}
{% load custome_filters %}


<div class="property-details-container">
    <!-- Property Details -->
    <div>
        {% for rental in property.property_rentals.all %}
            <div class="d-flex justify-content-between align-items-center">
                <h2>{{ property.name|title }} - {{ property.get_property_type_display }}</h2>
                <div class="dropdown">
                    <i class="bi bi-three-dots fs-3" style="cursor: pointer" data-bs-toggle="dropdown" aria-expanded="false"></i>
                    <ul class="dropdown-menu dropdown-menu-end border-0 shadow-sm">
                        <li>
                            <a class="dropdown-item" hx-get="{% url 'edit_rental' rental.id %}" hx-target="#main-content">{% trans "Edit Rental" %}</a>
                        </li>
                        <li>
                            <a class="dropdown-item text-danger" data-bs-toggle="modal" data-bs-target="#emptyPropertyModal{{ property.id }}">{% trans "Empty" %}</a>
                        </li>
                    </ul>
                </div>
            </div>
            {% include "modals/empty_property_modal.html" %}
        {% endfor %}
        
        <p class="text-muted"><i class="bi bi-geo-alt-fill pe-1"></i> {{ property.get_country_display }}, {{ property.city }} - {{ property.address }}
        </p>

        {% for rental in property.property_rentals.all %}
            <h4 class="text-success">{{ rental.price|format_numbers }} {{ property.get_translated_currency }}/{{ rental.get_payment_period }}</h4>
        {% endfor %}
        
        <hr>

        <!-- Property Tabs -->
        <ul class="nav nav-tabs" id="propertyDetailsTab" role="tablist">
            {% if property.is_rented %}
                <li class="nav-item">
                    <button class="nav-link active" style="color: var(--primary-color)" id="overview-tab" data-bs-toggle="tab" data-bs-target="#overview" role="tab" aria-selected="true">
                        <i class="bi bi-house-fill p-1"></i>{% trans "Overview" %}
                    </button>
                </li>
                <li class="nav-item">
                    <button class="nav-link" style="color: var(--primary-color)" id="tenant-tab" data-bs-toggle="tab" data-bs-target="#tenant" role="tab">
                        <i class="bi bi-person-fill p-1"></i>{% trans "Tenant Info" %}
                    </button>
                </li>
                <li class="nav-item">
                    <button class="nav-link" style="color: var(--primary-color)" id="rental-history-tab" data-bs-toggle="tab" data-bs-target="#rental-history" role="tab">
                        <i class="bi bi-clock-history p-1"></i>{% trans "Rental History" %}
                    </button>
                </li>
            {% else %}
                <li class="nav-item">
                    <button class="nav-link active" id="rental-history-tab" data-bs-toggle="tab" data-bs-target="#rental-history" role="tab">
                        <i class="bi bi-clock-history p-1"></i>{% trans "Rental History" %}
                    </button>
                </li>
            {% endif %}
        </ul>

        <div class="tab-content mt-3" id="propertyDetailsTabContent">
            {% if property.is_rented %}
                <!-- Overview Tab -->
                <div class="tab-pane fade show active" id="overview" role="tabpanel">
                    <div class="card card-overview shadow-sm mb-4">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-6 mb-3">
                                    <p><i class="bi bi-calendar-event px-2"></i> <strong>{% trans "Rent start date" %}:</strong> {{ rent_property.start_date|date:"d M Y" }}</p>
                                </div>
                                <div class="col-md-6 mb-3">
                                    <p><i class="bi bi-calendar-event px-2"></i> <strong>{% trans "Rent end date" %}:</strong> {{ rent_property.end_date|date:"d M Y" }}</p>
                                </div>
                                <div class="col-md-6 mb-3">
                                    {% if rent_property.damage_deposit %}
                                        <p><i class="bi bi-bank px-2"></i><strong>{% trans "Damage deposit" %}:</strong> {{ rent_property.damage_deposit|format_numbers }} {{ property.get_translated_currency }}</p>
                                    {% else %}
                                        <p><i class="bi bi-bank px-2"></i><strong>{% trans "Damage deposit" %}:</strong> {% trans "N/A" %}</p>
                                    {% endif %}
                                </div>
                                <div class="col-md-6 mb-3">
                                    <p>
                                        <strong><i class="bi bi-currency-dollar px-2"></i>{% trans "Payment status (Current month)" %}: </strong>
                                        {% if rent_property.status == "pending" %}
                                            <span class="badge bg-secondary">{{ rent_property.get_status_display }}</span>
                                        {% elif rent_property.status == "overdue" %}
                                            <span class="badge bg-warning">{{ rent_property.get_status_display }}</span>
                                        {% elif rent_property.status == "paid" %}
                                            <span class="badge bg-success">{{ rent_property.get_status_display }}</span>
                                        {% endif %}
                                    </p>
                                </div>
                                <div class="col-md-6 mb-3">
                                    <p>
                                        <i class="bi bi-calendar-event px-2"></i><strong>{% trans "Next Payment" %}:</strong>
                                        {% if rent_property.get_next_payment %}
                                            {% trans "in" %} {{ rent_property.get_next_payment.1 }} {% trans "day" %}{{ rent_property.get_next_payment.1|pluralize }}
                                        {% else %}
                                            {% trans "No more Payments" %}
                                        {% endif %}
                                    </p>
                                </div>
                                <div class="col-md-6 mb-3">
                                    <p>
                                        <i class="bi bi-file-text px-2"></i> <strong>{% trans "Contract" %}:</strong>
                                        {% if rent_property.contract %}
                                            <a href="{{ rent_property.contract.url }}" target="_blank" class="text-primary text-decoration-underline">{% trans "View Contract" %}</a>
                                        {% else %}
                                                {% trans "N/A" %}
                                        {% endif %}
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Tenant Info Tab -->
                <div class="tab-pane fade" id="tenant" role="tabpanel">
                    <div class="card card-overview shadow-sm mb-4">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-6 mb-3">
                                    <p><strong>{% trans "Name" %}:</strong> {{ rent_property.tenant.name|title }}</p>
                                </div>
                                <div class="col-md-6 mb-3">
                                    <p><strong>{% trans "Phone Number" %}:</strong> {{ rent_property.tenant.phone_number }}</p>
                                </div>
                                <div class="col-md-6 mb-3">
                                    <p><strong>{% trans "ID image" %}:</strong> 
                                        {% if rent_property.tenant.id_image %}
                                            <a href="{{ rent_property.tenant.id_image.url }}" target="_blank" class="text-primary text-decoration-underline">{% trans "View ID Image" %}</a>
                                        {% else %}
                                            {% trans "N/A" %}
                                        {% endif %}
                                    </p>
                                </div>
                                <div id="mobile-buttons" class="d-none">
                                    <a href="tel:{{ rent_property.tenant.phone_number }}" class="btn btn-sm me-2 text-white rounded-5 px-3" style="background-color: var(--primary-color)">
                                        <i class="bi bi-telephone-fill"></i> {% trans "Call" %}
                                    </a>
                                    <a href="sms:{{ rent_property.tenant.phone_number }}" class="btn btn-success btn-sm rounded-5 px-3">
                                        <i class="bi bi-chat-dots-fill"></i> {% trans "Text" %}
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                 <!-- Rental History Tab -->
                <div class="tab-pane fade" id="rental-history" role="tabpanel">
                    <div class="card card-overview shadow-sm">
                        <div class="card-body table-responsive">
                            <table class="table table-borderless">
                                <thead>
                                    <tr>
                                        <th>{% trans "Tenant" %}</th>
                                        <th>{% trans "From" %}</th>
                                        <th>{% trans "To" %}</th>
                                        <th>{% trans "Options" %}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for rental_history in rental_histories %}
                                        <tr>
                                            <td>{{ rental_history.tenant.name|title }}</td>
                                            <td>{{ rental_history.start_date|date:"d M Y" }}</td>
                                            <td>{{ rental_history.end_date|date:"d M Y" }}</td>
                                            <td><a href="#" class="text-decoration-underline">{% trans "More" %}</a></td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            {% else %}
                <!-- Rental History Tab -->
                <div class="tab-pane {% if rental_histories %} active {% endif %}" id="rental-history" role="tabpanel">
                    <div class="card card-overview shadow-sm">
                        <div class="card-body table-responsive">
                            {% if rental_histories %}
                                <table class="table table-borderless">
                                    <thead>
                                        <tr>
                                            <th>{% trans "Tenant" %}</th>
                                            <th>{% trans "From" %}</th>
                                            <th>{% trans "To" %}</th>
                                            <th>{% trans "Options" %}</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for rental_history in rental_histories %}
                                            <tr>
                                                <td>{{ rental_history.tenant.name|title }}</td>
                                                <td>{{ rental_history.start_date|date:"d M Y" }}</td>
                                                <td>{{ rental_history.end_date|date:"d M Y" }}</td>
                                                <td><a href="#" class="text-decoration-underline">{% trans "More" %}</a></td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
</div>

<script>
    if (/Mobi|Android/i.test(navigator.userAgent)) {
        document.getElementById('mobile-buttons').classList.remove('d-none');
    }
</script>